/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './module';
class MainModuleInjector extends import0.ɵNgModuleInjector<import1.MainModule> {
  _MainModule_0:import1.MainModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.MainModule {
    this._MainModule_0 = new import1.MainModule();
    return this._MainModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.MainModule)) { return this._MainModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory<any>(MainModuleInjector,import1.MainModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvTWFjaW50b3NoIEhEIDIvRGV2ZWxvcG1lbnQvUHJvamVjdHMvYWZrbS9raW8vcmVsZWFzZXMva2lvLW5nMi1tYXJrZG93bi1mb290bm90ZXMvc3JjL21vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Wb2x1bWVzL01hY2ludG9zaCBIRCAyL0RldmVsb3BtZW50L1Byb2plY3RzL2Fma20va2lvL3JlbGVhc2VzL2tpby1uZzItbWFya2Rvd24tZm9vdG5vdGVzL3NyYy9tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
